<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\Files\Txt\" />
    <Folder Include="Assets\Images\" />
    <Folder Include="Assets\Files\Data\" />
    <Folder Include="Model\" />
    <Folder Include="Dictionary\" />
    <Folder Include="Services\" />
    <Folder Include="ViewModel\" />
  </ItemGroup>

</Project>
